### ISSUE TITLE
Two minor issues in ntlm library

### ISSUE THREAD

**Issue by kmansoft** [vadimi/go-http-ntlm#21]
Hi, these are minor but perhaps worth fixing.

1 - `FlagsToString` in negotiate_flags.go uses `NTLMSSP_`  prefix on all flags.... All except `NTLM_NEGOTIATE_OEM`.

Perhaps it should be changed to `NTLMSSP_NEGOTIATE_OEM`

2 - Inconsistent version info in `negotiate()` vs. `GenerateAuthenticateMessage`

In `negotiate` - version is 6.1 and build is 7601

In `GenerateAuthenticateMessage` - version is 5.1 and build is 2600

**Comment by vadimi** [comment]
@kmansoft thanks for reporting

1. `NTLM_NEGOTIATE_OEM` - this is how MS decided to call it `¯\_(ツ)_/¯`  [https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-nlmp/125f7a94-933e-4023-a146-a449e49bf774](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-nlmp/125f7a94-933e-4023-a146-a449e49bf774)
2. Fixed in https://github.com/vadimi/go-ntlm/commit/e7f1485eeefc148f7f9c18c69a00b6c88f6ff3b8

**Comment by vadimi** [comment]
v2.4.1 released, closing this issue
