### ISSUE TITLE
panic: slice bounds out of range in ntlm.ParseChallengeMessage

### ISSUE THREAD

**Issue by SkyN** [vadimi/go-http-ntlm#5]
Hello!

I have **https**, and i got a **panic: runtime error: slice bounds out of range
github.com/ThomsonReutersEikon/go-ntlm/ntlm.ParseChallengeMessage(0xc00001185c, 0x3, 0x3, 0x0, 0x0, 0x0)**

Reseache show that ParseChallengeMessage waits len(challengeBytes)>8 
challengeBytes calculated from head **WWW-Authenticate**
My head is:

Content-Type:text/xml; charset=utf-8
X-Ms-Invokeapp:1; RequireReadOnly
Access-Control-Allow-Origin:*
Access-Control-Allow-Methods:GET,PUT,POST,DELETE,OPTIONS
Date:Mon, 28 Jan 2019 09:12:07 GMT
Sprequestguid:7c5eba9e-b351-e021-0342-46fa6d063b01
Spiislatency:0
X-Content-Type-Options:nosniff
Server:Microsoft-IIS/8.5
Request-Id:7c5eba9e-b351-e021-0342-46fa6d063b01
X-Frame-Options:SAMEORIGIN
Sprequestduration:2
X-Powered-By:ASP.NET
**Www-Authenticate: NTLM**
Microsoftsharepointteamservices:15.0.0.4911
Access-Control-Allow-Headers:Origin, Content-Type, Accept
Content-Length:1533

**Comment by JimFicarra** [comment]
I'm experiencing this as well.  Is this project not maintained anymore?

**Comment by vadimi** [comment]
I'm having trouble reproducing the issue. I use this library for a few NTLM apps, but never experienced this error. More details would be helpful - like some more detailed http traces.

**Comment by JimFicarra** [comment]
Understood - I'll try to get some more detail but I tracked it down to a panic in the dependent library here on this line:

https://github.com/ThomsonReutersEikon/go-ntlm/blob/master/ntlm/message_challenge.go#L59

As @SkyN showed, the Www-Authenticate header comes across in a debug session with the value of NTLM - the code in message_challenge.go expects a 48 byte message with the challenge token used in the NTLM handshake (as I understand it).

https://github.com/vadimi/go-http-ntlm/blob/master/ntlmtransport.go#L61-L81
In the code just linked is where it gets the header value - the debug I ran shows that the header just has NTLM w/out the token.  When it's put through the decBase64 function it's a 3 byte slice of uint8s.  That gets passed to ParseChallengeMessage which ends up as **body**, and line 59 in _message_challenge.go_ is  where the out of bounds occurs since it's only a 3 byte slice (it's looking for the first 8)

A few other notes worth mentioning:

- This package is being used in conjunction with go-kit in a microservice to retrieve info from the NTLM-protected resource from within one of the methods.
- Using go 1.12.4
- The error is reproducible in Mac, Windows 10, and Ubuntu Linux
- The driver was working fine for about a month before it suddenly stopped - the error spit out was "illegal base64 data at input byte 8"
- To rule out environmental changes on the NTLM-protected resource itself, I tested forms of NTLM auth against the exact same http resource.  It works using both PowerShell and Postman.

It's entirely possible something changed on the NTLM resource but not sure why it would cease functioning in this package as PowerShell Invoke-RestMethod and Postman NTLM auth is able to auth.

I'll see if I can get more trace information documented here.

Thanks

**Comment by moshemarciano** [comment]
@vadimi I believe the issue is probably a non standard NTLM implementation and not the safest Challenge message code, I am looking into it

**Comment by vadimi** [comment]
@moshemarciano thanks for the url, I have a clear reproduction of the issue now. It looks like the library I'm using to parse NTLM messages is ignoring some flags of NTLMSSP Challenge message. I'll see if I can come up with a fix.

**Comment by vadimi** [comment]
I was able to come up with a fix and published [v2.1.0](https://github.com/vadimi/go-http-ntlm/releases/tag/v2.1.0). But to be honest this server (http://ntlm.herokuapp.com/) does not implement the right ntlm negotiation, so I wouldn't recommend using it for production as it's not really secure. Even Wireshark complains that `NTLMSS_CHALLENGE` message is malformed:

![image](https://user-images.githubusercontent.com/1156106/88001161-75b31b00-cacd-11ea-9a29-4d042430c970.png)

Not sure if other users were having the same issue. If 2.1.0 doesn't fix it, please let me know.

**Comment by moshemarciano** [comment]
@vadimi I can confirm this fixed the use case I mentioned above
and yes, seems like the only public NTLM testing server I found is non-standard.
thanks!
